blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/aseguragonzalez/python-seedwork/discussions
    about: For open-ended questions or design discussions, use GitHub Discussions.
