from seedwork.application import (
    BackgroundTask,
    BaseBackgroundTask,
    Command,
    CommandBus,
    CommandHandler,
    DomainEventBus,
    DomainEventBusPublisher,
    DomainEventBusSubscriber,
    DomainEventHandler,
    DomainEventPublisher,  # backwards-compat alias
    IntegrationEvent,
    IntegrationEventHandler,
    IntegrationEventPublisher,
    IntegrationEventRecord,
    Query,
    QueryBus,
    QueryHandler,
    Result,
    ResultError,
    TaskHandler,
    TaskScheduler,
)
from seedwork.application.outbox import (  # kept for backwards compat
    OutboxRecord,
    OutboxRepository,
    OutboxStatus,
)
from seedwork.domain import (
    AggregateRoot,
    DomainError,
    DomainEvent,
    DomainEventRecord,
    Entity,
    NullEntityIdError,
    Repository,
    UnitOfWork,
    ValueObject,
)
from seedwork.infrastructure import (
    BackgroundTaskRecord,
    CommandBusBuilder,
    DeferredDomainEventBus,
    DomainEventCoordinatorCommandBus,
    DomainEventFlushCommandBus,  # backwards-compat alias
    DomainEventPublishingRepository,
    InMemoryIntegrationEventOutboxRepository,
    InMemoryIntegrationEventPublisher,
    InMemoryOutboxRepository,  # backwards-compat alias
    InMemoryRepository,
    InMemoryTaskOutboxRepository,
    InMemoryTaskQueue,
    InMemoryTaskScheduler,
    IntegrationEventOutboxRecord,
    IntegrationEventOutboxRepository,
    OutboxIntegrationEventPublisher,
    OutboxTaskScheduler,
    QueryBusBuilder,
    RegistryCommandBus,
    RegistryQueryBus,
    RegistryTaskBus,
    TaskOutboxRecord,
    TaskOutboxRepository,
    TransactionalCommandBus,
    ValidationCommandBus,
    ValidationQueryBus,
)

__all__ = [
    # application — commands
    "Command",
    "CommandBus",
    "CommandHandler",
    "Result",
    "ResultError",
    # application — domain events
    "DomainEventBus",
    "DomainEventBusPublisher",
    "DomainEventBusSubscriber",
    "DomainEventHandler",
    "DomainEventPublisher",
    # application — queries
    "Query",
    "QueryBus",
    "QueryHandler",
    # application — integration events
    "IntegrationEvent",
    "IntegrationEventHandler",
    "IntegrationEventPublisher",
    "IntegrationEventRecord",
    # application — outbox (deprecated, kept for compat)
    "OutboxRecord",
    "OutboxRepository",
    "OutboxStatus",
    # application — background tasks
    "BackgroundTask",
    "BaseBackgroundTask",
    "TaskHandler",
    "TaskScheduler",
    # domain
    "AggregateRoot",
    "DomainEventRecord",
    "DomainError",
    "DomainEvent",
    "Entity",
    "NullEntityIdError",
    "Repository",
    "UnitOfWork",
    "ValueObject",
    # infrastructure — buses
    "CommandBusBuilder",
    "DeferredDomainEventBus",
    "DomainEventCoordinatorCommandBus",
    "DomainEventFlushCommandBus",
    "DomainEventPublishingRepository",
    "RegistryCommandBus",
    "RegistryTaskBus",
    "TransactionalCommandBus",
    "ValidationCommandBus",
    "ValidationQueryBus",
    # infrastructure — query
    "QueryBusBuilder",
    "RegistryQueryBus",
    # infrastructure — repositories
    "BackgroundTaskRecord",
    "InMemoryRepository",
    "InMemoryTaskQueue",
    "InMemoryTaskScheduler",
    # infrastructure — integration event publishers
    "InMemoryIntegrationEventPublisher",
    "OutboxIntegrationEventPublisher",
    # infrastructure — outboxes
    "InMemoryIntegrationEventOutboxRepository",
    "InMemoryOutboxRepository",
    "InMemoryTaskOutboxRepository",
    "IntegrationEventOutboxRecord",
    "IntegrationEventOutboxRepository",
    "OutboxTaskScheduler",
    "TaskOutboxRecord",
    "TaskOutboxRepository",
]
